# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2aa2466e9f07ca4f6bdc2ba5da98a15d64af9fa0f819fe0876c7e893597af76c7cab8add7607cc4914303f3cd7e399fb6839080e2939a5ed863554b40f1f82

test:
  secret_key_base: 49b19014d58eab60f4e117c8e7978c922c9b397957993971adbcbfea350e61d27b3f08ef99641114be422f0c9459d1fa5fe26f54f6b4b410cd15eccc4f3bc7c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
